"use strict";

const { cleanText, truncate } = require("./util");
const { buildMetaDescription } = require("./metaTemplates");
const { pickRandomStyleDirective } = require("./styleTemplates");

/**
 * The single prompt used for the combined vision+copy request, shared by
 * both Gemini and Groq so a mid-run provider switch never changes output
 * structure or house rules.
 *
 * NOTE: the AI is asked for "key_visual_detail", NOT a full meta
 * description anymore — the meta description is now built from templates
 * in code (see metaTemplates.js) using the title (brand + product name)
 * and this one short, visually-grounded detail phrase.
 */
function buildCombinedPromptText({ promptConfig, product, designer, modelMatch }) {
  const { detect, extra_rules, language, brand_name, banned_phrases } = promptConfig;
  const bannedList = (banned_phrases || []).join(", ");
  const existingDescriptionText = (product.descriptionHtml || "").replace(/<[^>]*>/g, " ").slice(0, 600);
  const styleDirective = pickRandomStyleDirective();

  return `You are doing TWO jobs in one pass for an e-commerce catalog: (1) a meticulous product-photo analyst, then (2) a fashion editorial writer — the kind who writes for a fashion magazine, not a generic AI product blurb.

VOICE: Write the way fashion-magazine editorial copy reads — specific, observational, confident, varied sentence rhythm (mix short and long sentences), grounded in real visual detail rather than generic praise. Not gushing, not exclamation-heavy, not templated marketing-speak. This is about THIS product only — no celebrities, no runway shows, no other brands or collections. The brand is always "${brand_name}" and the product is always the one described below; never substitute or reference any other brand or product name.

STEP 1 — LOOK AT THE IMAGE(S) FIRST. Identify ONLY what is clearly, visibly present. Focus on: ${detect}
Do this silently — you do not need to output this step separately, just use it as the factual basis for step 2. If something is not clearly visible, do not mention it or guess — leave it out entirely.

STEP 2 — WRITE THE FINAL COPY, grounded ONLY in what you actually saw in step 1 plus the context below. Never add specifications, measurements, fabric names (unless already in the existing title/description below), or care instructions that weren't confirmed.

PRODUCT CONTEXT:
- Title: ${product.title}
- Vendor: ${product.vendor || "(unknown)"}
- Existing description (for reference only — reuse any fabric name mentioned here, don't invent a new one): ${existingDescriptionText || "(none)"}

${designer ? `DESIGNER (confirmed, you may name them): ${designer.name}` : "DESIGNER: none confirmed — do not name any designer."}
${modelMatch ? `MODEL/CELEBRITY (confirmed, may mention by name once): ${modelMatch.name}` : "MODEL/CELEBRITY: none confirmed — do NOT name or describe any person in the photo."}

BRAND: ${brand_name}
WRITE IN: ${language || "English"}

STRUCTURE for description_html this time (clean semantic HTML; if headings are used, start at H2/H3 since the theme already renders an H1 title) — follow this specific approach:
${styleDirective}

HARD RULES (apply regardless of which structure above is used):
- ${extra_rules}
- Never use these overused phrases or close variants: ${bannedList}.
- Vary sentence length — reflect what's actually different about THIS product, don't template it.
- No exclamation-mark-heavy marketing voice, no generic superlatives ("stunning", "must-have") unless visibly earned.

Also produce:
- "key_visual_detail": ONE short, factual, lowercase phrase (3-6 words, max ~35 characters) naming the single most distinctive thing you can actually see — e.g. "floral embroidery", "vertical stripe pattern", "tassel detailing on neckline". This must be visibly true — never invented. This is used elsewhere, not shown verbatim in the description.
- "tags": an array of 6-10 relevant SEO tags (lowercase, no # symbol), based only on confirmed attributes + product type + designer name if confirmed.
- "image_alt_text": a single reusable alt text template (max 125 characters) describing the product generically for its images, e.g. "Embroidered festive kurti with round neckline by ${designer ? designer.name : brand_name}".

Respond ONLY with a JSON object, no markdown fences, in this exact shape:
{
  "description_html": "<p>...</p>...",
  "key_visual_detail": "...",
  "tags": ["...", "..."],
  "image_alt_text": "..."
}`;
}

/**
 * Shared post-processing for either provider's raw JSON response:
 * - enforces length limits in code (never trusts the model on this)
 * - builds the meta description from templates (title + key_visual_detail)
 * - inserts designer collection link / model Instagram link / brand link
 *   directly in code — these are NEVER generated by the model
 */
function postProcessResult(result, { promptConfig, product, designer, modelMatch }) {
  result.description_html = cleanText(result.description_html);
  result.tags = Array.isArray(result.tags) ? result.tags.slice(0, 10) : [];
  result.image_alt_text = truncate(cleanText(result.image_alt_text), 125);

  result.meta_description = buildMetaDescription({
    title: product.title,
    detail: result.key_visual_detail,
    fallbackBrand: promptConfig.brand_name,
    minChars: promptConfig.meta_description_min_chars || 150,
    maxChars: promptConfig.meta_description_max_chars || 160,
  });

  let html = result.description_html;

  if (designer && designer.collection_url && html.includes(designer.name)) {
    const headingRegex = new RegExp(`(<h2[^>]*>)(\\s*${designer.name}[^<]*)(</h2>)`, "i");
    if (headingRegex.test(html)) {
      html = html.replace(headingRegex, `$1<a href="${designer.collection_url}">$2</a>$3`);
    } else {
      // This structure variant didn't use an H2 heading — link the first
      // plain-text mention of the designer's name instead, so the
      // collection link still lands regardless of which style was picked.
      html = html.replace(designer.name, `<a href="${designer.collection_url}">${designer.name}</a>`);
    }
  }

  if (modelMatch && modelMatch.instagram && html.includes(modelMatch.name)) {
    html = html.replace(modelMatch.name, `<a href="${modelMatch.instagram}" rel="nofollow">${modelMatch.name}</a>`);
  }

  html += `\n<p><a href="${promptConfig.brand_url}">${promptConfig.brand_name}</a></p>`;

  result.description_html = html;
  result.designer_matched = designer ? designer.name : null;
  result.model_matched = modelMatch ? modelMatch.name : null;

  return result;
}

module.exports = { buildCombinedPromptText, postProcessResult };
